cats99/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats 

  resource :cat_rental_requests, only: [:new, :create]

  resources :cats do 
    resources :cat_rental_requests
  end

end

cats99/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats99/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  description :text             not null
#  name        :string           not null
#  sex         :string(1)        not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper


    validates :birth_date, :name, :sex, :description, presence: true
    validates :color, presence: true, inclusion: {in: %w(Red Black Blue White Green Yellow), message: "%{value} is invalid color"}

    has_many :rental_requests,
        primary_key: :id,
        foreign_key: :cat_id,
        class_name: :CatRentalRequest,
        dependent: :destroy

    def age
        age = Date.today.year - self.birth_date.year
    end

end

cats99/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint           not null, primary key
#  end_date   :date             not null
#  start_date :date             not null
#  status     :string           default("PENDING"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  cat_id     :integer          not null
#
# Indexes
#
#  index_cat_rental_requests_on_cat_id  (cat_id)
#
class CatRentalRequest < ApplicationRecord
    validates :status, presence: true, inclusion: {in: %w(PENDING APPROVED DENIED), message: "Invalid Status"}
    validates :cat_id, :start_date, :end_date, presence: true
    # validates :cat_id, uniqueness: {scope: :name}

    belongs_to :cat, 
        primary_key: :id,
        foreign_key: :cat_id,
        class_name: :Cat

    def overlapping_request
        CatRentalRequest.select(:status).where.not("start_date > end_date OR end_date < start_date")
    end

    def overlapping_approved_requests
        overlapping_request.where(status: 'APPROVED')
    end

    def does_not_overlap_approved_request
        if overlapping_approved_requests.any?
            return false
        end
        true
    end

end

cats99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

cats99/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

    def new
        @cats = Cat.all
        render :new
    end
  
    def create
        @cat = Cat.find_by(id: rental_request_params[:cat_id])
        @rental_request = CatRentalRequest.new(rental_request_params)
  
        if @rental_request.save
        # show user the rental_request show page
            redirect_to cat_rental_requests_url(@rental_request)
        else
        # show user the new rental_request form
            render :new
        end
    end
  
    private
    def rental_request_params
      params.require(:cat_rental_requests).permit(:cat_id, :start_date, :end_date, :status)
    end
  
end

cats99/app/controllers/cats_controller.rb
class CatsController < ApplicationController

      def index
        @cats = Cat.all
        render :index
      end
    
      def show
        @cat = Cat.find_by(id: params[:id])
    
        if @cat
          render :show
        else
          redirect_to cat_url
        end
      end
    
      def new
        @cat = Cat.new
        render :new
      end
    
      def create
        @cat = Cat.new(cat_params)
    
        if @cat.save
          # show user the cat show page
          redirect_to cat_url(@cat)
        else
          # show user the new cat form
          render :new
        end
      end
    
      def edit
        @cat = Cat.find_by(id: params[:id])
        render :edit
      end
    
      def update
        @cat = Cat.find_by(id: params[:id])
    
        if @cat.update_attributes(cat_params)
          redirect_to cat_url(@cat)
        else
          render :edit
        end
      end
    
      private
      def cat_params
        params.require(:cat).permit(:birth_date, :color, :name, :sex,:description)
      end
    
end

cats99/app/helpers/application_helper.rb
module ApplicationHelper
end

cats99/app/views/cat_rental_requests/new.html.erb
<h1> Request your cat! </h1>

<form action="<%= cat_rental_requests %>" method="post">
<label for="request">Choose a cat</label>
<select id="request" name="cat_rental_request[cat_id]">
<option disabled selected>-- Please Select Cat --</option>
<% @cats.each do |cat|%>
    <option value="<%= cat.name %>"><%= cat.name %></option>
<% end %>
</select>

cats99/app/views/cats/_form.html.erb
<% if action == :edit %>
  <% action_url = cat_url(cat)%>
<% else %>
  <% action_url = cats_url %>
<% end %>

<form action="<%= action_url %>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label for="name">Name</label>
  <input id="name" type="text" name="cat[name]" value="<%= cat.name %>">

  <br>

  <label for="birth_date">Birthday</label>
  <input id="birth_date" type="date" name="cat[birth_date]" value="<%= cat.birth_date %>">

  <br>

  <label for="color">Color</label>
  <select id="color" name="cat[:color]">
    <option disabled <%= cat.color ? "" : "selected"%>>-- Please Select Cat Color--</option>
    <option value="Red" <%= cat.color == "Red" ? "selected" : ""%> >Red</option>
    <option value="Blue" <%= cat.color == "Blue" ? "selected" : ""%> >Blue</option>
    <option value="Black" <%= cat.color == "Black" ? "selected" : ""%> >Black</option>
  </select>
  <br>
  <label for="sex">Sex</label>
  <input id="sex" type="radio" name="cat[sex]" value="M" <%= cat.sex=='M' ? 'checked' : '' %>  > M 
  <input id="sex" type="radio" name="cat[sex]" value="F" <%= cat.sex=='F' ? 'checked' : '' %> > F
  <br>
  <label for="description">Description</label>
  <br>
  <textarea name="cat[description]">
    <%= cat.description %>
  </textarea>
  <br>
  <input type="submit" value="<%= action == :edit ? 'update cat' : 'add cat'%>">

cats99/app/views/cats/edit.html.erb
<h1> Edit a cat! </h1>
<%= render 'form', action: :edit, cat: @cat %>

cats99/app/views/cats/index.html.erb
<h1> Meow, I am a cat :3 ! </h1>

<ul>
  <% @cats.each do |cat| %>
    <li><%= cat.name %></li>
  <% end %>
</ul>

cats99/app/views/cats/new.html.erb
<h1> Create a new cat! </h1>
<%= render 'form', action: :new, cat: @cat %>

cats99/app/views/cats/show.html.erb
<table>
    <thead>
        <tr>
            <th colspan="2"><%= @cat.name%></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td> Birth Date: <%= @cat.birth_date%> </td>
        </tr>

        <tr>
            <td> Color: <%= @cat.color%></td>
        </tr>

        <tr>
            <td> Sex: <%= @cat.sex%> </td>
        </tr>

        <tr>
            <td> Description: <%= @cat.description%></td>
        </tr>
    </tbody>
</table>

cats99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>